### this file is used for testing apis

### GET: categories
GET http://localhost:3001/categories
Accept: application/json

### POST: categories
POST http://localhost:3001/categories
Content-Type: application/json

{
  "category_name": "Tomatoes",
  "created_at": "2022/12/29",
  "updated_at": "2022/12/29"
}

### GET: categories/id
GET http://localhost:3001/categories/1
Accept: application/json

### PUT: categories/edit/id
PUT http://localhost:3001/categories/edit/1
Content-Type: application/json

{
  "category_name": "Onions",
  "created_at": "2022/12/29",
  "updated_at": "2022/12/29"
}

### POST: categories/delete/id
POST http://localhost:3001/categories/delete/1
Content-Type: application/json

{}

### GET: products
GET http://localhost:3001/products
Accept: application/json

### POST: products
POST http://localhost:3001/products
Content-Type: application/json

{
  "category_id": 2,
  "product_name": "Orange",
  "unit_price": "800",
  "created_at": "2023/01/14",
  "updated_at": "2023/01/14"
}

### GET: products/id
GET http://localhost:3001/products/1
Accept: application/json

### PUT: products/edit/id
PUT http://localhost:3001/products/edit/1
Content-Type: application/json

{
  "category_id": 1,
  "product_name": "Amstel Royale",
  "unit_price": "2200",
  "created_at": "2023/01/14",
  "updated_at": "2023/01/14"
}

### POST: products/delete/id
POST http://localhost:3001/products/delete/1
Content-Type: application/json

{}

### POST: orders
GET http://localhost:3001/orders
Accept: application/json

### POST: orders
POST http://localhost:3001/orders
Content-Type: application/json

{
  "customer_id": 1,
  "product_id": 2,
  "qty": 2,
  "total": 3200,
  "created_at": "2023/01/18",
  "updated_at": "2023/01/18"
}

### GET: orders/id
GET http://localhost:3001/orders/1
Accept: application/json

### PUT: orders/edit/id
PUT http://localhost:3001/orders/edit/1
Content-Type: application/json

{
  "customer_id": 1,
  "product_id": 2,
  "qty": 4,
  "total": 6400,
  "created_at": "2023/01/18",
  "updated_at": "2023/01/18"
}

### c
POST http://localhost:3001/orders/delete/1
Content-Type: application/json

{}
